### ISSUE TITLE
Node label colour

### ISSUE THREAD

**Issue by Flobian** [hackl/tikz-network#3]
When I create nodes with the \node command I can change the label colour, e.g. with
\node at (0,0)[font=\footnotesize,orange]{\textbf{A}};

Is there any way to achieve this when I import node information from a .csv file through the \Vertices command?

**Comment by hackl** [comment]
I added the commands to the `\Vertex` commands. With the options `\fontsize=\footnotesize` and `\fontcolor =  orange` you can now change the font size and color. Additionally, you can change the font size continuously with the option `\fontscale=number`, where 1 is default size and e.g. 2 is an increase of 200%.  These options are available for both, vertices and edges. I updated the example `ex_complex_01.tex` accordingly.

Unfortunately, you cannot use the command = `\fontsize` in the `.csv`, because there is still a bug. Meanwhile, you have to use the command `\fontscale` if you like to have different font sizes per vertices/edges. If you only like to change the font size (for all vertices/edges), you can use `\SetVertexStyle[TextFont=\footnotesize]`.
